name: Check That Imports Are Sorted

on:
  pull_request:

jobs:
  Check-Imports-Sorted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv sync --only-group isort

      - name: Check that imports are sorted with isort
        run: |
          uv run isort --check --quiet --diff .
