name: Release
on:
  push:
    tags:
      - v*


jobs:
  Release:
    name: Release {{ cookiecutter.hyphenated }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build run id of this sha
        env:
          GH_TOKEN: {% raw %}${{ secrets.GHA_CLI_PAT }}{% endraw %}
        run: |
          shaRunId="$(gh api /repos/hmrd-forpeople/{{ cookiecutter.hyphenated }}/actions/workflows/build.yml/runs --method get -f status=success -f head_sha={% raw %}${{ github.sha }}{% endraw %} --jq ".workflow_runs[0].id")"
          echo 'SHA_RUN_ID='$shaRunId >> $GITHUB_ENV
      - name: Download built binaries
        uses: actions/download-artifact@v5
        with:
          pattern: {{ cookiecutter.hyphenated }}-*-{% raw %}${{ github.sha }}{% endraw %}
          repository: {% raw %}${{ github.repository }}{% endraw %}
          github-token: {% raw %}${{ secrets.GHA_PAT }}{% endraw %}
          run-id: {% raw %}${{ env.SHA_RUN_ID }}{% endraw %}
      - name: Make binaries executable
        run: |
          chmod +x {{ cookiecutter.hyphenated }}-*/*
      - name: Rename binaries
        run: |
          mv {{ cookiecutter.hyphenated }}-macos-{% raw %}${{ github.sha }}{% endraw %}/{{ cookiecutter.hyphenated }} {{ cookiecutter.hyphenated }}-macos
          mv {{ cookiecutter.hyphenated }}-linux-{% raw %}${{ github.sha }}{% endraw %}/{{ cookiecutter.hyphenated }} {{ cookiecutter.hyphenated }}-linux
          mv {{ cookiecutter.hyphenated }}-windows-{% raw %}${{ github.sha }}{% endraw %}/{{ cookiecutter.hyphenated }}.exe {{ cookiecutter.hyphenated }}-windows.exe
      - name: Remove directories
        run: |
          rmdir {{ cookiecutter.hyphenated }}-macos-{% raw %}${{ github.sha }}{% endraw %}
          rmdir {{ cookiecutter.hyphenated }}-linux-{% raw %}${{ github.sha }}{% endraw %}
          rmdir {{ cookiecutter.hyphenated }}-windows-{% raw %}${{ github.sha }}{% endraw %}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: {% raw %}${{ secrets.GHA_RELEASE_PAT }}{% endraw %}
          name: {{ cookiecutter.hyphenated }}-{% raw %}${{ github.ref_name }}{% endraw %}
          files: |
            {{ cookiecutter.hyphenated }}-macos
            {{ cookiecutter.hyphenated }}-linux
            {{ cookiecutter.hyphenated }}-windows.exe
