name: Release
on:
  push:
    tags:
      - v*


jobs:
  Release:
    name: Release {{ cookiecutter.hyphenated }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build run id of this sha
        env:
          GH_TOKEN: ${{ secrets.GHA_CLI_PAT }}
        run: |
          shaRunId="$(gh api /repos/hmrd-forpeople/{{ cookiecutter.hyphenated }}/actions/workflows/build.yml/runs --method get -f status=success -f head_sha=${{ github.sha }} --jq ".workflow_runs[0].id")"
          echo 'SHA_RUN_ID='$shaRunId >> $GITHUB_ENV
      - name: Download built binaries
        uses: actions/download-artifact@v5
        with:
          pattern: {{ cookiecutter.hyphenated }}-*-${{ github.sha }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GHA_PAT }}
          run-id: ${{ env.SHA_RUN_ID }}
      - name: Make binaries executable
        run: |
          chmod +x {{ cookiecutter.hyphenated }}-*/*
      - name: Rename binaries
        run: |
          mv {{ cookiecutter.hyphenated }}-macos-${{ github.sha }}/{{ cookiecutter.hyphenated }} {{ cookiecutter.hyphenated }}-macos
          mv {{ cookiecutter.hyphenated }}-linux-${{ github.sha }}/{{ cookiecutter.hyphenated }} {{ cookiecutter.hyphenated }}-linux
          mv {{ cookiecutter.hyphenated }}-windows-${{ github.sha }}/{{ cookiecutter.hyphenated }}.exe {{ cookiecutter.hyphenated }}-windows.exe
      - name: Remove directories
        run: |
          rmdir {{ cookiecutter.hyphenated }}-macos-${{ github.sha }}
          rmdir {{ cookiecutter.hyphenated }}-linux-${{ github.sha }}
          rmdir {{ cookiecutter.hyphenated }}-windows-${{ github.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GHA_RELEASE_PAT }}
          name: {{ cookiecutter.hyphenated }}-${{ github.ref_name }}
          files: |
            {{ cookiecutter.hyphenated }}-macos
            {{ cookiecutter.hyphenated }}-linux
            {{ cookiecutter.hyphenated }}-windows.exe
