name: Security Scan

on: pull_request

jobs:
  Security-Scan:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv sync --only-group bandit
      - name: Security scan using bandit
        run: |
          uv run bandit -ll -f txt -c pyproject.toml -r .
